import { Schema, model, Document, Types } from "mongoose";

// ─── Types ────────────────────────────────────────────────────────────────────

export type JobStatus =
  | "open" | "matched" | "accepted" | "in_progress"
  | "completed" | "cancelled" | "expired";

export type UrgencyLevel = "low" | "medium" | "high";

interface GeoJSONPoint {
  type: "Point";
  coordinates: [number, number];
}

export interface IJobPost {
  clientId: Types.ObjectId;

  // ── Core Fields ───────────────────────────────────────────────────────────
  title: string;
  category: string;
  serviceType: string;   // Canonical field used by agents (mirrors category)

  // ── Raw + AI-Generated Descriptions (Phase 5) ─────────────────────────────
  rawInput?: string;        // Original user message — verbatim
  descriptionEN?: string;   // English description — generated by Agent 1
  descriptionUR?: string;   // Urdu script — generated by Agent 1
  descriptionRU?: string;   // Roman Urdu — generated by Agent 1
  aiSummary?: string;       // Short 1-line summary (for mobile cards)
  aiGeneratedAt?: Date;

  // ── Intent Fields ─────────────────────────────────────────────────────────
  urgency: UrgencyLevel;
  preferredTime?: string;
  description: string;

  // ── Location ──────────────────────────────────────────────────────────────
  location: GeoJSONPoint;
  address: string;
  area?: string;
  city: string;

  // ── Budget ────────────────────────────────────────────────────────────────
  budgetMinPKR: number;
  budgetMaxPKR: number;
  agreedPricePKR?: number;
  budgetRange?: { min: number; max: number };  // Alias for agent compatibility

  // ── Status & Assignment ───────────────────────────────────────────────────
  status: JobStatus;
  assignedProviderId?: Types.ObjectId;
  matchedProviderIds?: Types.ObjectId[];

  // ── TTL ───────────────────────────────────────────────────────────────────
  expiresAt: Date;

  createdAt?: Date;
  updatedAt?: Date;
}

export interface IJobPostDocument extends IJobPost, Document {
  _id: Types.ObjectId;
}

// ─── Schema ───────────────────────────────────────────────────────────────────

const GeoJSONPointSchema = new Schema<GeoJSONPoint>(
  {
    type:        { type: String, enum: ["Point"], required: true, default: "Point" },
    coordinates: {
      type: [Number],
      required: true,
      validate: {
        validator: (v: number[]) =>
          v.length === 2 && v[0] >= -180 && v[0] <= 180 && v[1] >= -90 && v[1] <= 90,
        message: "coordinates must be [longitude, latitude]",
      },
    },
  },
  { _id: false }
);

const JOB_STATUSES: JobStatus[] = [
  "open", "matched", "accepted", "in_progress",
  "completed", "cancelled", "expired",
];

const JobPostSchema = new Schema<IJobPostDocument>(
  {
    clientId: {
      type: Schema.Types.ObjectId, ref: "User",
      required: [true, "clientId is required"], index: true,
    },

    // Core
    title:       { type: String, required: true, trim: true, minlength: 5, maxlength: 120 },
    category:    { type: String, required: true, trim: true, index: true },
    serviceType: { type: String, trim: true, default: "" }, // set by orchestrator

    // AI-generated descriptions
    rawInput:     { type: String, trim: true },
    descriptionEN:{ type: String, trim: true },
    descriptionUR:{ type: String, trim: true },
    descriptionRU:{ type: String, trim: true },
    aiSummary:    { type: String, trim: true, maxlength: 300 },
    aiGeneratedAt:{ type: Date },

    // Intent
    urgency: {
      type: String,
      enum: ["low", "medium", "high"] as UrgencyLevel[],
      default: "medium",
    },
    preferredTime: { type: String, trim: true },
    description:   { type: String, required: true, trim: true, maxlength: 2000 },

    // Location
    location: { type: GeoJSONPointSchema, required: [true, "location is required"] },
    address:  { type: String, required: true, trim: true },
    area:     { type: String, trim: true },
    city:     { type: String, required: true, trim: true, index: true },

    // Budget
    budgetMinPKR: { type: Number, required: true, min: 0 },
    budgetMaxPKR: { type: Number, required: true },
    agreedPricePKR: { type: Number, min: 0 },
    budgetRange: {
      type: { min: Number, max: Number },
      _id: false,
    },

    // Status
    status: {
      type: String,
      enum: { values: JOB_STATUSES, message: "Invalid job status" },
      default: "open",
      index: true,
    },
    assignedProviderId: { type: Schema.Types.ObjectId, ref: "Provider" },
    matchedProviderIds: { type: [Schema.Types.ObjectId], ref: "Provider", default: [] },

    // TTL — auto-delete 0 seconds after expiresAt (= 24h from creation)
    expiresAt: {
      type: Date,
      required: true,
      default: () => new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
  },
  { timestamps: true, versionKey: false }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

JobPostSchema.index({ location: "2dsphere" });
JobPostSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });      // TTL
JobPostSchema.index({ status: 1, city: 1, createdAt: -1 });
JobPostSchema.index({ status: 1, serviceType: 1 });

// ─── Export ───────────────────────────────────────────────────────────────────

const JobPost = model<IJobPostDocument>("JobPost", JobPostSchema);
export default JobPost;
