import { DashboardMetric, MessageThread } from "@/types";

/**
 * Centered Mock Data for Mahir Phases 2 & 3.
 * Strictly follows requirements in §10 of the Master Prompt.
 */

export const MOCK_PROVIDERS: any[] = [
  {
    id: "1",
    name: "Ali AC Services",
    rating: 4.8,
    distance: "2.1km",
    onTimeScore: 98,
    priceEstimate: 1150,
    verifiedBadge: true,
    reasoning: "Selected due to 4.8 stars and 0 cancellations in 30 days",
    score: 91.4,
    matchFactors: {
      distance: 0.9,
      rating: 0.95,
      onTime: 0.98,
      specialization: 1.0,
      cancellationRate: 1.0,
      sentiment: 0.9,
    },
  },
  {
    id: "2",
    name: "Hassan Electricals",
    rating: 4.5,
    distance: "1.4km",
    onTimeScore: 87,
    priceEstimate: 900,
    verifiedBadge: false,
    reasoning: "Closer but lower reliability score",
    score: 78.2,
    matchFactors: {
      distance: 1.0,
      rating: 0.9,
      onTime: 0.87,
      specialization: 0.8,
      cancellationRate: 0.9,
      sentiment: 0.7,
    },
  },
];

export const MOCK_REASONING_STEPS = [
  "Parsing your request in Roman Urdu...",
  "Identified: AC Repair, G-13, Tomorrow Morning",
  "Searching 23 active providers in your area...",
  "Analyzing 6 match factors for each provider...",
  "Calculating urgency-adjusted pricing...",
  "Match found. Showing top 2 results.",
];

export const MOCK_DASHBOARD_METRICS: DashboardMetric[] = [
  {
    id: "1",
    icon: "ac_unit",
    title: "Fix my AC",
    subtitle: "Visit: Rs 500 • ETA: 20 mins",
  },
  {
    id: "2",
    icon: "plumbing",
    title: "Need Plumber",
    subtitle: "ETA: 15 mins",
  },
  {
    id: "3",
    icon: "electric_bolt",
    title: "Electrician Urgent",
    subtitle: "Urgency High",
    isUrgent: true,
  },
];

export const MOCK_BOOKINGS: any[] = [
  {
    id: "b1",
    serviceType: "AC Technician",
    providerName: "Ali AC Services",
    status: "confirmed",
    scheduledTime: "Tomorrow, 10:00 AM",
    totalEstimate: 1150,
    area: "G-13, Islamabad",
  },
  {
    id: "b2",
    serviceType: "Plumber",
    providerName: "Hassan Electricals",
    status: "completed",
    scheduledTime: "May 15, 2026",
    totalEstimate: 900,
    area: "F-7, Islamabad",
  },
];

export const MOCK_PROVIDER_METRICS: DashboardMetric[] = [
  {
    id: "1",
    icon: "location_on",
    title: "Nearby Jobs",
    subtitle: "5 new in Islamabad",
  },
  {
    id: "2",
    icon: "calendar_today",
    title: "My Schedule",
    subtitle: "Next at 2:00 PM",
  },
  {
    id: "3",
    icon: "account_balance_wallet",
    title: "Today's Earnings",
    subtitle: "Rs. 4,500",
  },
];

export const MOCK_AVAILABLE_JOBS: any[] = [
  {
    id: "1",
    title: "Urgent: 1.5 Ton AC Service",
    location: "G-13/4, Islamabad",
    estimatedPrice: "PKR 1,500 – 2,500",
    aiSummary: "Client reported that the indoor unit is dripping water. Needs immediate attention.",
    generatedBy: "Generated by AI Agent",
    timeAgo: "2 mins ago",
    distance: "2.1 km",
    clientRating: 4.8,
  },
  {
    id: "2",
    title: "Plumbing: Sink Leak Repair",
    location: "F-8 Markaz, Islamabad",
    estimatedPrice: "PKR 800 – 1,200",
    aiSummary: "Kitchen sink drain pipe is leaking. Requires seal replacement or pipe tightening.",
    generatedBy: "Generated by AI Agent",
    timeAgo: "15 mins ago",
    distance: "3.5 km",
    clientRating: 4.5,
  },
];

export const MOCK_THREADS: MessageThread[] = [
  {
    id: "t1",
    name: "Mahir Support",
    lastMessage: "Your request is being processed.",
    timestamp: "10:42 AM",
    isUnread: true,
  },
  {
    id: "t2",
    name: "Ali (AC Expert)",
    lastMessage: "Main 10 baje tak pohanch jaunga.",
    timestamp: "9:15 AM",
    isUnread: false,
  },
  {
    id: "t3",
    name: "Usama Khan",
    lastMessage: "Thanks for the quick response!",
    timestamp: "Yesterday",
    isUnread: false,
  },
];

export const MOCK_ACTIVE_JOB: any = {
  id: "aj1",
  title: "Fix AC Cooling Issue",
  status: "in_progress",
  location: "G-13/4, House 12, Islamabad",
  scheduledTime: "Today, 2:30 PM",
  clientName: "Yasir Khan",
  estimatedEarnings: "Rs 2,500",
  checklist: [
    { id: "c1", label: "Accepted", status: "completed" },
    { id: "c2", label: "En-route to client", status: "completed" },
    { id: "c3", label: "Work in progress", status: "active" },
  ],
};

