import { useState, useEffect, useCallback } from "react";
import type { ProviderJob } from "@/types";
import apiClient from "@/services/api";
import { AxiosError } from "axios";

interface UseProviderJobsResult {
  jobs: ProviderJob[];
  isLoading: boolean;
  error: Error | null;
  refresh: () => Promise<void>;
}

// ─── API Response Types ───────────────────────────────────────────────────────

interface JobPostFromApi {
  _id: string;
  title: string;
  description?: string;
  descriptionEN?: string;
  area?: string;
  address?: string;
  city?: string;
  urgency?: string;
  budgetMinPKR?: number;
  budgetMaxPKR?: number;
  distanceKm?: number;
  createdAt?: string;
}

interface NearbyJobsResponse {
  success: boolean;
  count: number;
  data: JobPostFromApi[];
}

import { MOCK_AVAILABLE_JOBS } from "@/constants/mockData";

/**
 * Custom hook for Provider Jobs Feed.
 * For Phase 3: Uses mock data from constants/mockData.ts.
 * (Real GET /api/provider/jobs API call commented out).
 */
export const useProviderJobs = (): UseProviderJobsResult => {
  const [jobs, setJobs] = useState<ProviderJob[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetchJobs = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);

      // Hardcoding G-13 coordinates for the demo
      const { data: response } = await apiClient.get<NearbyJobsResponse>("/api/provider/jobs?lat=33.6844&lng=72.9774&radiusKm=10");

      if (!response.success) {
        throw new Error("Failed to fetch nearby jobs");
      }

      // Map backend JobPost format to ProviderJob format expected by the UI
      const formattedJobs: ProviderJob[] = (response.data || []).map((job: any) => ({
        id: job._id,
        title: job.title || "New Request",
        location: job.area || job.address || "Islamabad",
        estimatedPrice: `PKR ${job.budgetMinPKR || 500} - ${job.budgetMaxPKR || 2000}`,
        aiSummary: job.descriptionEN || "Client needs immediate assistance.",
        generatedBy: "Generated by AI Agent",
        timeAgo: job.createdAt ? getTimeAgo(new Date(job.createdAt)) : "Just now",
        distance: job.distanceKm ? `${job.distanceKm.toFixed(1)} km` : "Nearby",
        clientRating: 4.8, // Mock client rating since clients don't have ratings yet
      }));

      // Fallback to mock data if DB is completely empty (though we just seeded it!)
      setJobs(formattedJobs.length > 0 ? formattedJobs : MOCK_AVAILABLE_JOBS);

    } catch (err) {
      console.error("Provider Jobs Error:", err);
      // Fallback to mock data so the demo doesn't fail
      setJobs(MOCK_AVAILABLE_JOBS);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchJobs();
  }, [fetchJobs]);

  return { jobs, isLoading, error, refresh: fetchJobs };
};

// ─── Helper ───────────────────────────────────────────────────────────────────

function getTimeAgo(date: Date): string {
  const diffMs = Date.now() - date.getTime();
  const mins = Math.floor(diffMs / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins} min${mins > 1 ? "s" : ""} ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours} hr${hours > 1 ? "s" : ""} ago`;
  const days = Math.floor(hours / 24);
  return `${days} day${days > 1 ? "s" : ""} ago`;
}
